background_opacity          0.6
cursor_trail                1
window_padding_width        25
allow_remote_control        yes

include themes/noctalia.conf
map alt+shift+enter launch --type=os-window --cwd=current
